export const SERVICE_HISTORY_AVAILABLE = "SERVICE_HISTORY_AVAILABLE";

export const CREATE_SERVICE = "CREATE_SERVICE";
export const SERVICE_SELECTED = "SERVICE_SELECTED";
export const SELECTED_SERVICE_UPDATED = "SELECTED_SERVICE_UPDATED";
export const SERVICE_DELETED = "SERVICE_DELETED";

export const CREATE_SERVICE_ITEM = "CREATE_SERVICE_ITEM";
export const SERVICE_ITEM_SELECTED = "SERVICE_ITEM_SELECTED";
export const SELECTED_SERVICE_ITEM_UPDATED = "SELECTED_SERVICE_ITEM_UPDATED";
export const SERVICE_ITEM_DELETED = "SERVICE_ITEM_DELETED";
